### ISSUE TITLE
Generate documentation for inferred properties

### ISSUE THREAD

**Issue by jmaliksi** [jmaliksi/blaseball-mike#83]
We should figure out a good way to list out all the properties on the models that get read dynamically from the json so that they're visible in the HTML docs

Could do have a manually run script that looks at canonical historical data like the ones used in unit tests maybe, generate some local file, then feed that into the docs maybe? Or maybe generate a website where you can click around on the various models and have it load the latest?

Maybe there's a halfway step where at least the live models can use `self.fields` to output something on method call, which I believe was my initial intent, so at least someone working in the repl has something.

cc @Edgarware

**Comment by Edgarware** [comment]
We could probably just write a script using pdoc3 as a library instead of using its built in CLI. Then we can just load a JSON for each class at doc-generation time and add the fields as instance variables (assuming they aren't already there). This would only catch new fields when we re-run the doc generation scripts, but it's something.
